// TODO: Add Support for object shorthand properties
export const FILM_ACTIONS = {
    GETALLFILMS: 'GETALLFILMS',
    GETALLFILMS_RESOLVED: 'GETALLFILMS_RESOLVED',
    GETALLFILMS_REJECTED: 'GETALLFILMS_REJECTED',

    UPDATEFILMDETAIL: 'UPDATEFILMDETAIL',
    UPDATEFILMDETAIL_RESOLVED: 'UPDATEFILMDETAIL_RESOLVED',
    UPDATEILMDETAIL_REJECTED: 'UPDATEFILMDETAIL_REJECTED'

};
