// TODO: Add Support for object shorthand properties
export const FILM_ACTIONS = {
    GETALLFILMS: 'GETALLFILMS',
    GETALLFILMS_RESOLVED: 'GETALLFILMS_RESOLVED',
    GETALLFILMS_REJECTED: 'GETALLFILMS_REJECTED',

    UPDATEFILMDETAIL: 'UPDATEFILMDETAIL',
    UPDATEFILMDETAIL_RESOLVED: 'UPDATEFILMDETAIL_RESOLVED',
    UPDATEILMDETAIL_REJECTED: 'UPDATEFILMDETAIL_REJECTED',

    DELETEFILM: 'DELETEFILM',
    DELETEFILM_RESOLVED: 'DELETEFILM_RESOLVED',
    DELETEFILM_REJECTED: 'DELETEFILM_REJECTED',

    ADDFILM: 'ADDFILM',
    ADDFILM_RESOLVED: 'ADDFILM_RESOLVED',
    ADDFILM_REJECTED: 'ADDFILM_REJECTED'
};
