// TODO: Add Support for object shorthand properties
export const USER_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGIN_RESOLVED: 'LOGIN_RESOLVED',
    LOGIN_REJECTED: 'LOGIN_REJECTED',
    LOGOUT: 'LOGOUT',
    LOGOUT_RESOLVED: 'LOGOUT_RESOLVED',
    LOGOUT_REJECTED: 'LOGOUT_REJECTED',
    SIGNUP: 'SIGNUP',
    SIGNUP_RESOLVED: 'SIGNUP_RESOLVED',
    SIGNUP_REJECTED: 'SIGNUP_REJECTED',
};
